const notFoundError = (res) => {
    return res.status(404).send("Essa tarefa n√£o foi encontrada!!!");
};
module.exports = {
    notFoundError,
};
